name:                aoc2017
version:             0.1.0.0
github:              "martstol/aoc2017"
license:             MIT
author:              "Martin Stølen"
maintainer:          "martstol@gmail.com"
copyright:           "2017 Martin Stølen"

extra-source-files:
- README.md

synopsis:            Advent of Code 2017
description:         Please see the README on Github at <https://github.com/martstol/aoc2017#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -O2

library:
  source-dirs:
  - src
  dependencies:
  - containers
  - array

executables:
  aoc2017-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - aoc2017
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N

tests:
  aoc2017-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - aoc2017
    - tasty
    - tasty-hspec
    - tasty-auto
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N

